import {
  Content1,
  Content10,
  Content11,
  Content12,
  Content13,
  Content14,
  Content15,
  Content16,
  Content17,
  Content2,
  Content3,
  Content4,
  Content5,
  Content6,
  Content7,
  Content8,
  Content9,
} from "@/ui components/Contents";
import {
  Header1,
  Header2,
  Header3,
  Header4,
  Header5,
} from "@/ui components/Headers";
import {
  Hero1,
  Hero10,
  Hero2,
  Hero3,
  Hero4,
  Hero5,
  Hero6,
  Hero7,
  Hero8,
  Hero9,
} from "@/ui components/Heroes";
import { Blog1, Blog2, Blog3, Blog4, Blog5 } from "@/ui components/blogs";
import { Cta1, Cta2, Cta3, Cta4, Cta5, Cta6 } from "@/ui components/ctas";
import { Faq1, Faq2, Faq3, Faq4 } from "@/ui components/faqs";
import {
  Feature1,
  Feature10,
  Feature11,
  Feature12,
  Feature2,
  Feature3,
  Feature4,
  Feature5,
  Feature6,
  Feature7,
  Feature8,
  Feature9,
} from "@/ui components/features";
import {
  Footer1,
  Footer2,
  Footer3,
  Footer4,
  Footer5,
  Footer6,
} from "@/ui components/footers";
import { Form1, Form2, Form3, Form4 } from "@/ui components/forms";
import {
  Pricing1,
  Pricing10,
  Pricing2,
  Pricing3,
  Pricing4,
  Pricing5,
  Pricing6,
  Pricing7,
  Pricing8,
  Pricing9,
} from "@/ui components/pricings";
import {
  Testimonial1,
  Testimonial2,
  Testimonial3,
  Testimonial4,
  Testimonial5,
} from "@/ui components/testimonials";

const {
  Navigation1,
  Navigation2,
  Navigation3,
  Navigation4,
  Navigation5,
} = require("@/ui components/Navbars");

export const comps = {
  navigation1: () => <Navigation1 />,
  navigation2: () => <Navigation2 />,
  navigation3: () => <Navigation3 />,
  navigation4: () => <Navigation4 />,
  navigation5: () => <Navigation5 />,
  blog1: () => <Blog1 />,
  blog2: () => <Blog2 />,
  blog3: () => <Blog3 />,
  blog4: () => <Blog4 />,
  blog5: () => <Blog5 />,

  //   card1: () => <Card1 />,

  content1: () => <Content1 />,
  content2: () => <Content2 />,
  content3: () => <Content3 />,
  content4: () => <Content4 />,
  content5: () => <Content5 />,
  content6: () => <Content6 />,
  content7: () => <Content7 />,
  content8: () => <Content8 />,
  content9: () => <Content9 />,
  content10: () => <Content10 />,
  content11: () => <Content11 />,
  content12: () => <Content12 />,
  content13: () => <Content13 />,
  content14: () => <Content14 />,
  content15: () => <Content15 />,
  content16: () => <Content16 />,
  content17: () => <Content17 />,

  cta1: () => <Cta1 />,
  cta2: () => <Cta2 />,
  cta3: () => <Cta3 />,
  cta4: () => <Cta4 />,
  cta5: () => <Cta5 />,
  cta6: () => <Cta6 />,

  faq1: () => <Faq1 />,
  faq2: () => <Faq2 />,
  faq3: () => <Faq3 />,
  faq4: () => <Faq4 />,

  feature1: () => <Feature1 />,
  feature2: () => <Feature2 />,
  feature3: () => <Feature3 />,
  feature4: () => <Feature4 />,
  feature5: () => <Feature5 />,
  feature6: () => <Feature6 />,
  feature7: () => <Feature7 />,
  feature8: () => <Feature8 />,
  feature9: () => <Feature9 />,
  feature10: () => <Feature10 />,
  feature11: () => <Feature11 />,

  footer1: () => <Footer1 />,
  footer2: () => <Footer2 />,
  footer3: () => <Footer3 />,
  footer4: () => <Footer4 />,
  footer5: () => <Footer5 />,
  footer6: () => <Footer6 />,

  form1: () => <Form1 />,
  form2: () => <Form2 />,
  form3: () => <Form3 />,

  header1: () => <Header1 />,
  header2: () => <Header2 />,
  header3: () => <Header3 />,
  header4: () => <Header4 />,
  header5: () => <Header5 />,

  hero1: () => <Hero1 />,
  hero2: () => <Hero2 />,
  hero3: () => <Hero3 />,
  hero4: () => <Hero4 />,
  hero5: () => <Hero5 />,
  hero6: () => <Hero6 />,
  hero7: () => <Hero7 />,
  hero8: () => <Hero8 />,
  hero9: () => <Hero9 />,
  hero10: () => <Hero10 />,

  pricing1: () => <Pricing1 />,
  pricing2: () => <Pricing2 />,
  pricing3: () => <Pricing3 />,
  pricing4: () => <Pricing4 />,
  pricing5: () => <Pricing5 />,
  pricing6: () => <Pricing6 />,
  pricing7: () => <Pricing7 />,
  pricing8: () => <Pricing8 />,
  pricing9: () => <Pricing9 />,
  pricing10: () => <Pricing10 />,

  //   signins: () => <Signins />,
  //   signups: () => <Signups />,
  //   sliders: () => <Sliders />,
  //   stats: () => <Stats />,
  //   steps: () => <Steps />,
  //   teams: () => <Teams />,

  testimonial1: () => <Testimonial1 />,
  testimonial2: () => <Testimonial2 />,
  testimonial3: () => <Testimonial3 />,
  testimonial4: () => <Testimonial4 />,
  testimonial5: () => <Testimonial5 />,
};
